# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
    npm run build
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifactName: 'drop'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/build'
    artifact: 'react-app'
    publishLocation: 'pipeline'

# - script: |
#     az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
#     az storage blob delete-batch --source "\$web" --pattern "*" --account-name "$(storageAccountName)" --account-key "$(storageAccountKey)"
#     az storage blob upload-batch --destination "\$web" --source "$(System.DefaultWorkingDirectory)/$(artifactPath)/build" --account-name "$(storageAccountName)" --account-key "$(storageAccountKey)"
#     az logout
#   displayName: 'Upload Artifacts to Azure Storage'